backendSpecific:
  OpenAI-Compatible:
    tokens:
    - token: null
      endpoint: https://api.deepseek.com
      modelName: deepseek-v4-flash
    tokenStrategy: random
    checkAvailable: true
    stream: true
    apiTimeout: 120
    apiErrorWait: auto
  SakuraLLM:
    endpoints:
    - http://127.0.0.1:8080
    rewriteModelName: ''
plugin:
  filePlugin: file_galtransl_json
  textPlugins:
  - text_common_normalfix
  file_galtransl_json:
    output_with_src: false
common:
  gpt.numPerRequestTranslate: 10
  workersPerProject: 16
  sortBy: size
  language: zh-cn
  splitFile: Num
  splitFileNum: 2048
  splitFileCrossNum: 0
  save_steps: 1
  start_time: ''
  linebreakSymbol: auto
  skipH: false
  smartRetry: true
  retranslFail: false
  retranslKey:
  - 关键字重翻：命中缓存problem或pre_jp关键字的句子会被重翻；去掉#可启用，也可自定义关键字。
  - 翻译失败
  gpt.contextNum: 8
  gpt.translation_guideline: Basic.md
  gpt.enhance_jailbreak: false
  gpt.change_prompt: 'no'
  gpt.token_limit: 0
  loggingLevel: info
  saveLog: false
proxy:
  enableProxy: false
  proxies: []
problemAnalyze:
  problemList:
  - 词频过高
  - 标点错漏
  - 残留日文
  - 多加换行
  - 比日文长
  - 字典使用
  - 语言不通
  - 缺控制符
dictionary:
  defaultDictFolder: Dict
  usePreDictInName: false
  usePostDictInName: false
  useGPTDictInName: false
  sortDict: true
  preDict:
  - (project_dir)dict_pre.txt
  gpt.dict:
  - (project_dir)dict_gpt.txt
  postDict:
  - (project_dir)dict_after.txt
